# Generated by Django 4.0 on 2021-12-30 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_handler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='full_url',
            new_name='long_url',
        ),
        migrations.RenameField(
            model_name='urls',
            old_name='shortened_url',
            new_name='short_url',
        ),
    ]
