# Generated by Django 4.0 on 2021-12-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_handler', '0002_rename_full_url_urls_long_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
